"""
Signup Email Agent
Processes new user signups: classifies ICP fit and generates a personalized welcome email.
"""

import os
import json
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from pydantic import BaseModel, Field
from typing import Literal

# ── Load keys from .env ───────────────────────────────────────────────────────
load_dotenv()

os.environ["LANGSMITH_TRACING"] = "true"
os.environ["LANGSMITH_PROJECT"] = os.getenv(
    "LANGCHAIN_PROJECT", "langsmith-signup-email-agent"
)


# ── Structured output schema ──────────────────────────────────────────────────
class SignupEmailOutput(BaseModel):
    to: str = Field(description="Email address")
    icp_fit: Literal["high", "medium", "low", "unknown"] = Field(
        description="ICP fit classification"
    )
    reason: str = Field(description="Brief reasoning for classification")
    subject: str = Field(description="Email subject line")
    body: str = Field(description="Email body text")


# ── System prompt (improved) ──────────────────────────────────────────────────
SYSTEM_PROMPT = """
You process signups for a dev tool SaaS called 'Glop' and generate a personalized welcome email.

Return: icp_fit, reason, and a welcome email (subject + body).

ICP fit guidance:
- high:    engineering/product leader at a tech or SaaS company, 50+ employees
- medium:  developer or technical role at any company
- low:     non-technical role or very small company (<10 employees)
- unknown: insufficient information to classify

Email rules:
- Subject: make it specific to the person's role or company, not just "Welcome to Glop"
- Opening: greet by first name only if provided; otherwise use a generic greeting
- Body: in 2–3 short sentences, connect Glop's value to their specific role and company context
  - high ICP: emphasize team productivity, scaling, or engineering velocity
  - medium ICP: emphasize individual developer workflow and speed
  - low ICP: keep it warm and simple, no jargon — always use first name if provided
  - unknown: keep it generic and inviting
- Closing: one simple next-step CTA (e.g. "Explore your dashboard" or "Check out our quick-start guide")
- Tone: concise, professional, human — no buzzwords, no filler phrases
- Under 120 words total
- Do NOT mention details absent from the input
- Do NOT confuse 'Glop' with the user's company name
"""

# ── LLM-as-a-Judge: Personalization Quality ───────────────────────────────────
JUDGE_PROMPT = """
You are evaluating the personalization quality of a welcome email generated by an AI agent.

First check: does the input contain ANY personalizable data (first name, role, or company)?
- If NO personalizable data exists in the input, return: {"score": "n/a", "reason": "no personalizable data in input"}

If YES, then score:
Score 1 if the email:
- Addresses the user by first name (if provided in the input)
- References their specific role or company (if provided in the input)
- Connects Glop's value to their specific context (not just generic benefits)

Score 0 if the email:
- Uses only generic greetings when a name was available
- Ignores the user's role or company when they were provided
- Gives only generic value props with no connection to the user's context

Return ONLY a JSON object in this exact format:
{"score": 1, "reason": "brief explanation"}
{"score": 0, "reason": "brief explanation"}
{"score": "n/a", "reason": "brief explanation"}
"""

def judge_personalization(input_text: str, email_body: str) -> dict:
    """Score 0 or 1 for personalization quality."""
    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
    response = llm.invoke([
        SystemMessage(content=JUDGE_PROMPT),
        HumanMessage(content=f"INPUT:\n{input_text}\n\nEMAIL BODY:\n{email_body}")
    ])
    try:
        return json.loads(response.content)
    except Exception:
        return {"score": 0, "reason": f"Parse error: {response.content}"}


# ── LLM with structured output ────────────────────────────────────────────────
_llm = ChatOpenAI(model="gpt-4o-mini", temperature=0).with_structured_output(
    SignupEmailOutput
)


class _Agent:
    def invoke(self, payload: dict) -> dict:
        messages = payload.get("messages", [])
        lc_messages = [SystemMessage(content=SYSTEM_PROMPT)]
        for m in messages:
            if m["role"] == "user":
                lc_messages.append(HumanMessage(content=m["content"]))
        structured_response = _llm.invoke(lc_messages)
        return {"structured_response": structured_response}


agent = _Agent()


# ── Golden dataset + judge ────────────────────────────────────────────────────
if __name__ == "__main__":
    test_cases = [
        {
            "name": "Baseline - High ICP",
            "input": """email: sarah@acmecorp.com
first_name: Sarah
company_name: Acme Corp
role: VP of Engineering
industry: SaaS
company_size: 500"""
        },
        {
            "name": "Edge: Missing first name",
            "input": """email: user@techcorp.com
company_name: TechCorp
role: Software Engineer
industry: SaaS
company_size: 200"""
        },
        {
            "name": "Edge: Generic email domain",
            "input": """email: john.smith@gmail.com
first_name: John
role: Developer"""
        },
        {
            "name": "Edge: Unclear role",
            "input": """email: alex@startupco.com
first_name: Alex
company_name: StartupCo
role: Associate
company_size: 25"""
        },
        {
            "name": "Edge: Stealth company",
            "input": """email: founder@stealth.io
first_name: Maya
role: CEO
company_size: 8"""
        },
        {
            "name": "Edge: Incomplete context",
            "input": """email: someone@company.com"""
        },
    ]

    scores = []
    for tc in test_cases:
        print(f"\n{'='*60}")
        print(f"TEST: {tc['name']}")
        print('='*60)
        result = agent.invoke({
            "messages": [{"role": "user", "content": f"Process this signup:\n{tc['input']}"}]
        })
        output = result["structured_response"]
        print(f"ICP Fit:  {output.icp_fit}")
        print(f"Reason:   {output.reason}")
        print(f"Subject:  {output.subject}")
        print(f"Body:\n{output.body}")

        judgment = judge_personalization(tc["input"], output.body)
        print(f"\n⚖️  Personalization Score: {judgment['score']} — {judgment['reason']}")
        scores.append({"test": tc["name"], "score": judgment["score"]})

    print(f"\n{'='*60}")
    print("PERSONALIZATION SCORE SUMMARY")
    print('='*60)
    for s in scores:
        if s["score"] == "n/a":
            icon = "⏭️ "
        elif s["score"] == 1:
            icon = "✅"
        else:
            icon = "❌"
        print(f"{icon}  {s['test']}: {s['score']}")
    scorable = [s for s in scores if s["score"] != "n/a"]
    total = sum(s["score"] for s in scorable)
    print(f"\nTotal: {total}/{len(scorable)} (excluding n/a cases)")